"""initial schema

Revision ID: 0a3fa5002f94
Revises: 
Create Date: 2026-05-14 18:57:47.941959
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0a3fa5002f94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
